/* autoconf.h.  Generated by configure.  */

/* Define to 1 if you have the `inet_aton' function. */
#undef HAVE_INET_ATON

/* Define to 1 if you have the `gmp' library (-lgmp). */
/* #undef HAVE_LIBGMP */

/* Define to 1 if you have the `crypto' library (-lcrypto). */
#define HAVE_LIBCRYPTO 1

/* Define to 1 if you have the `vsnprintf' function. */
#undef HAVE_SNPRINTF

/* Define to 1 if you have the `vsnprintf' function. */
#undef HAVE_VSNPRINTF

/* Define to 1 if you have the <unistd.h> header file. */
#undef HAVE_UNISTD_H


#ifdef HAVE_LIBGMP
#undef HAVE_LIBCRYPTO
#endif
